apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: flask
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: bopgeek/flask-web:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: flask-svc
spec:
  ports:
  - nodePort: 32223
    port: 60
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
  type: NodePort